---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# cureplots

<!-- badges: start -->
<!-- badges: end -->

The goal of cureplots is to ...

## Installation

You can install the development version of cureplots from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gbasulto/cureplots")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(cureplots)
library(ggplot2)
## basic example code

set.seed(2000)

## Define parameters
beta <- c(-1, 0.3, 3)

## Simulate idependent variables
n <- 900
AADT <- c(runif(n, min = 2000, max = 150000))
nlanes <- sample(x = c(2, 3, 4), size = n, replace = TRUE)
LNAADT <- log(AADT)

## Simulate dependent variable
theta <- exp(beta[1] + beta[2] * LNAADT + beta[3] * nlanes)
y <- rpois(n, theta)

## Fit model
mod <- glm(y ~ LNAADT + nlanes, family = poisson)

## Calculate residuals
res <- residuals(mod)

## Calculate CURE plot data
cure_df <- calculate_cure_dataframe(AADT, res)

head(cure_df)

calculate_cure_dataframe(LNAADT, res) |>
  ggplot() +
  geom_line(aes(x = LNAADT, y = cumres), linewidth = 0.9, colour = "#112446") +
  geom_line(aes(x = LNAADT, y = upper), linewidth = 0.75, colour = "red") +
  geom_line(aes(x = LNAADT, y = lower), linewidth = 0.75, colour = "red") +
  labs(x = "LNAADT", y = "Cumulative Residuals") +
  theme_light()


calculate_cure_dataframe(AADT, res) |>
  ggplot() +
  geom_line(aes(x = AADT, y = cumres), linewidth = 0.9, colour = "#112446") +
  geom_line(aes(x = AADT, y = upper), linewidth = 0.75, colour = "red") +
  geom_line(aes(x = AADT, y = lower), linewidth = 0.75, colour = "red") +
  labs(x = "AADT", y = "Cumulative Residuals") +
  theme_light()
```

Test: 
```{r, eval = FALSE}

cure_df <- calculate_cure_dataframe(AADT, res)

cure_plot <- function(x, covariate = NULL) {
  ## x is cure_dataframe or model
  
}

```


<!-- 
To do list 
1. dd 
2. ccc 
-->

